.\" This file is distributed under the same license as the iptux
.\" package.
.\" Copyright (C) LI Daobing <lidaobing@gmail.com>, 2008.
.\"
.TH "IPTUX" 1 "2008-11-02" "" ""
.SH NAME
iptux \- IP Messanger client

.SH "SYNOPSIS"
.B iptux

.SH "DESCRIPTION"

.PP
iptux is an IP Messenger client for Linux. For more information on IP
Messanger, check http://www.ipmsg.org/index.html.en .

.PP
iptux support:
.TP 4
  \- auto detect other clients in the intranet.
.TP
  \- send message to other clients.
.TP
  \- send file to other clients.

.PP
Homepage: http://code.google.com/p/iptux

.SH "FILES"
\fI~/.config/iptux\fR: users' local settings directory

.SH "SEE ALSO"
.BR pidgin(1)
